#!/usr/bin/env python
"""
Run all the Jupyter notebook tutorials. Usage:
  ./run_tutorials

It will execute all notebooks in parallel, print out any errors
encountered, and print a summary of results.

NB: The execute() function was drafted in part via ChatGPT.
"""

import os
import sciris as sc
import nbformat
import nbconvert.preprocessors as nbp
import utils as ut

folder = sc.path(__file__).resolve().parent # Ensure it's the real path if it's symlinked




if __name__ == '__main__':
    results = main()

