#!/bin/bash
# Run the integration tests.
# Be sure to install the test requirements first!
#    pip install -r requirements.txt

# Non-interactive plots
export SCIRIS_BACKEND='agg'

# Run the tests
pytest test_*.py -n auto --ignore=manual --durations=0
