"""
Test the machine-readable API index (api.json, llms.txt), which is generated by docs/make_api.py when the docs are built.
"""
import sys
import sciris as sc
import starsim as ss
import starsim.library as ssl

sys.path.insert(0, str(sc.thispath(__file__).parent / 'docs')) # The generator lives in the docs folder
import make_api # noqa


def test_make_index():
    sc.heading('Test generating the API index')

    index = make_api.make_index()
    entries = index['entries']
    names = [entry['name'] for entry in entries]

    print(f'Index has {len(entries)} entries for v{index["version"]}')
    assert len(entries) > 150, 'Expecting the index to cover most of the Starsim API'
    assert index['version'] == ss.__version__
    assert names == sorted(names, key=str.lower), 'Entries should be sorted by name, for stable diffs'
    assert len(names) == len(set(names)), 'Entries should be unique'

    print('Checking entries')
    namespaces = dict(ss=ss, ssl=ssl)
    for entry in entries:
        name = entry['name']
        prefix, attr = name.split('.')
        assert hasattr(namespaces[prefix], attr), f'{name} is in the index but not in the Starsim namespace'
        assert entry['kind'] in ['function', 'class'], f'Unexpected kind for {name}'
        assert entry['signature'].startswith('('), f'Invalid signature for {name}'
        assert entry['summary'], f'No summary for {name}'
        assert ' at 0x' not in str(entry['pars']), f'Default pars for {name} include a memory address, so are not reproducible'

    print('Checking known entries')
    entrydict = {entry['name']:entry for entry in entries}
    assert entrydict['ss.SIR']['pars']['beta'] == 'ss.peryear(0.1)', 'Expecting ss.SIR to list its default pars'
    assert entrydict['ss.Sim']['example'], 'Expecting ss.Sim to have an example'
    assert entrydict['ssl.Cholera']['module'] == 'library.diseases'
    for alias,canonical in index['aliases'].items():
        assert alias not in names, f'Alias {alias} should not have its own entry'

    return index


def test_llms_txt():
    sc.heading('Test generating llms.txt')

    index = make_api.make_index()
    for examples in [False, True]:
        text = make_api.make_llms_txt(index, examples=examples)
        assert text.startswith(f'# Starsim v{ss.__version__}')
        assert '## Diseases (ss.diseases)' in text
        assert '## Library: diseases (ssl.diseases)' in text
        for entry in index['entries']: # Every entry should appear
            assert f'`{entry["name"]}(' in text, f'{entry["name"]} is missing from llms.txt'
        print(f'llms.txt (examples={examples}): {len(text)/1e3:0.1f} kB')

    full = make_api.make_llms_txt(index, examples=True)
    assert len(full) > len(make_api.make_llms_txt(index, examples=False)), 'Expecting examples to make the file longer'

    return full


if __name__ == '__main__':
    T = sc.timer()

    index = test_make_index()
    text = test_llms_txt()

    T.toc('Done.')
