# API reference {.doc .doc-index}

## API reference

Full details on all classes and functions.

### Basics

| | |
| --- | --- |
| [sim](sim.qmd#starsim.sim) | Define core Sim classes |
| [loop](loop.qmd#starsim.loop) | Parent class for the integration loop. |
| [people](people.qmd#starsim.people) | Defines the People class and functions associated with making people |
| [parameters](parameters.qmd#starsim.parameters) | Set parameters |

### Modules

| | |
| --- | --- |
| [modules](modules.qmd#starsim.modules) | General module class -- base class for diseases, interventions, etc. Also |
| [disease](disease.qmd#starsim.disease) | Base classes for diseases |
| [networks](networks.qmd#starsim.networks) | Networks that connect people within a population |
| [demographics](demographics.qmd#starsim.demographics) | Define pregnancy, deaths, migration, etc. |
| [interventions](interventions.qmd#starsim.interventions) | Define interventions |
| [products](products.qmd#starsim.products) | Define products |

### Workflows

| | |
| --- | --- |
| [run](run.qmd#starsim.run) | Utilities for running in parallel |
| [calibration](calibration.qmd#starsim.calibration) | Define the calibration class |

### Utilities

| | |
| --- | --- |
| [arrays](arrays.qmd#starsim.arrays) | Define array-handling classes, including agent states |
| [time](time.qmd#starsim.time) | Functions and classes for handling time |
| [distributions](distributions.qmd#starsim.distributions) | Define random-number-safe distributions. |
| [results](results.qmd#starsim.results) | Result structures. |
| [samples](samples.qmd#starsim.samples) | Create a class for storing a large number of simulations. |
| [settings](settings.qmd#starsim.settings) | Define options for Starsim. |
| [utils](utils.qmd#starsim.utils) | Numerical utilities |