project:
  type: website
  output-dir: _build/html
  title: "Starsim"
  execute-dir: file
  render:
    - "*.md"
    - "*.qmd"
    - "*.ipynb"
    # - "!tutorials/"
    # - "!user_guide/"

jupyter: python3
execute:
  enabled: false
  daemon: true  # Use Jupyter daemon mode
  cache: true   # Cache execution results
  error: false
  echo: true
  warning: true
  kernel: python3
  executor: local-parallel

website:
  title: "Starsim"
  favicon: images/favicon.ico
  navbar:
    logo: images/idm-logo-transparent.png
    left:
      - href: index.qmd
        text: Home
      - href: tutorials.qmd
        text: Tutorials
      - href: user_guide.qmd
        text: User guide
      - href: whatsnew.qmd
        text: What's new
      - href: conduct.qmd
        text: Code of Conduct
      - href: contributing.qmd
        text: Contributing
      - href: api/index.qmd
        text: API reference
  sidebar:
    style: docked
    collapse-level: 2
    contents:
      - section: "Tutorials"
        contents:
          - tut_intro.ipynb
          - tut_buildsim.ipynb
          - tut_demographics.ipynb
          - tut_diseases.ipynb
          - tut_transmission.ipynb
          - tut_interventions.ipynb
      - section: "User guide"
        contents:
        - section: "Introduction"
          contents:
          - guide_starsim.ipynb
          - guide_spokes.ipynb
        - section: "Basic concepts"
          contents:
          - guide_model.ipynb
          - guide_sim.ipynb
          - guide_people.ipynb
        - section: "Modules"
          contents:
          - guide_diseases.ipynb
          - guide_networks.ipynb
          - guide_demographics.ipynb
          - guide_interventions.ipynb
          - guide_analyzers.ipynb
          - guide_connectors.ipynb
        - section: "Workflows"
          contents:
          - guide_run.ipynb
          - guide_calibration.ipynb
          - guide_samples.ipynb
          - guide_cloud.ipynb
        - section: "Advanced topics"
          contents:
          - guide_time.ipynb
          - guide_indexing.ipynb
          - guide_parameters.ipynb
          - guide_distributions.ipynb
          - guide_random.ipynb
          - guide_profiling.ipynb
          - guide_nonstandard.ipynb
      - href: whatsnew.qmd
        text: What's new
      - href: conduct.qmd
        text: Code of Conduct
      - href: contributing.qmd
        text: Contributing
      - href: api/index.qmd
        text: API reference

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: _static/theme_overrides.css
    toc: true
    toc-depth: 3
    page-layout: full
    code-copy: true
    code-tools: true
    highlight-style: github

quartodoc:
  package: starsim
  title: API reference
  dir: api
  parser: google
  sections:
    - title: API reference
      desc: Full details on all classes and functions.
      contents:
        - arrays
        - calibration
        - demographics
        - disease
        - distributions
        - interventions
        - loop
        - modules
        - networks
        - parameters
        - people
        - products
        - results
        - run
        - samples
        - settings
        - sim
        - time
        - utils
