project:
  type: website
  output-dir: _build/html
  title: "Starsim"
  execute-dir: file
  render:
    - "*.md"
    - "*.qmd"
    - "*.ipynb"
    # - "!tutorials/"
    # - "!user_guide/"

jupyter: python3
execute:
  enabled: true
  daemon: true  # Use Jupyter daemon mode
  cache: true   # Cache execution results
  error: false
  echo: true
  warning: true
  kernel: python3
  executor: local-parallel

website:
  title: "Starsim"
  favicon: images/favicon.ico
  navbar:
    logo: images/idm-logo-transparent.png
    left:
      - href: index.qmd
        text: Home
      - href: tutorials.qmd
        text: Tutorials
      - href: user_guide.qmd
        text: User guide
      - href: whatsnew.qmd
        text: What's new
      - href: conduct.qmd
        text: Code of Conduct
      - href: contributing.qmd
        text: Contributing
      - href: api/index.qmd
        text: API reference
  sidebar:
    style: docked
    collapse-level: 2
    contents:
      - section: "Tutorials"
        contents:
          - tutorials/intro.ipynb
          - tutorials/buildsim.ipynb
          - tutorials/demographics.ipynb
          - tutorials/diseases.ipynb
          - tutorials/transmission.ipynb
          - tutorials/interventions.ipynb
      - section: "User guide"
        contents:
        - section: "Introduction"
          contents:
          - user_guide/intro_starsim.ipynb
          - user_guide/intro_spokes.ipynb
        - section: "Basic concepts"
          contents:
          - user_guide/basics_model.ipynb
          - user_guide/basics_sim.ipynb
          - user_guide/basics_people.ipynb
        - section: "Modules"
          contents:
          - user_guide/modules_diseases.ipynb
          - user_guide/modules_networks.ipynb
          - user_guide/modules_demographics.ipynb
          - user_guide/modules_interventions.ipynb
          - user_guide/modules_analyzers.ipynb
          - user_guide/modules_connectors.ipynb
        - section: "Workflows"
          contents:
          - user_guide/workflows_run.ipynb
          - user_guide/workflows_calibration.ipynb
          - user_guide/workflows_samples.ipynb
          - user_guide/workflows_cloud.ipynb
        - section: "Advanced topics"
          contents:
          - user_guide/advanced_time.ipynb
          - user_guide/advanced_indexing.ipynb
          - user_guide/advanced_parameters.ipynb
          - user_guide/advanced_distributions.ipynb
          - user_guide/advanced_random.ipynb
          - user_guide/advanced_profiling.ipynb
          - user_guide/advanced_nonstandard.ipynb
      - href: whatsnew.qmd
        text: What's new
      - href: conduct.qmd
        text: Code of Conduct
      - href: contributing.qmd
        text: Contributing
      - href: api/index.qmd
        text: API reference

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: _static/theme_overrides.css
    toc: true
    toc-depth: 3
    page-layout: full
    code-copy: true
    code-tools: true
    highlight-style: github

quartodoc:
  package: starsim
  title: API reference
  dir: api
  parser: google
  sections:
    - title: API reference
      desc: Full details on all classes and functions.
      contents:
        - arrays
        - calibration
        - demographics
        - disease
        - distributions
        - interventions
        - loop
        - modules
        - networks
        - parameters
        - people
        - products
        - results
        - run
        - samples
        - settings
        - sim
        - time
        - utils
