project:
  type: website
  output-dir: _build/html
  title: "Starsim"
  execute-dir: file

jupyter: python3
execute:
  enabled: true
  daemon: true  # Use Jupyter daemon mode
  cache: true   # Cache execution results
  freeze: true  # Freeze computational outputs
  output-dir: _freeze  # Store outputs separately
  error: false
  echo: true
  warning: true
  kernel: python3
  thread-count: 4  # Number of threads for parallel execution

website:
  title: "Starsim"
  favicon: images/favicon.ico
  navbar:
    logo: images/idm-logo-transparent.png
    left:
      - href: index.qmd
        text: Home
      - href: tutorials.qmd
        text: Tutorials
      - href: user_guide.qmd
        text: User guide
      - href: whatsnew.qmd
        text: What's new
      - href: conduct.qmd
        text: Code of Conduct
      - href: contributing.qmd
        text: Contributing
      - href: api/index.qmd
        text: API reference
  sidebar:
    style: docked
    collapse-level: 3
    contents:
      - section: "Tutorials"
        contents:
          - tutorials/tut_intro.ipynb
          - tutorials/tut_buildsim.ipynb
          - tutorials/tut_demographics.ipynb
          - tutorials/tut_diseases.ipynb
          - tutorials/tut_transmission.ipynb
          - tutorials/tut_interventions.ipynb
      - section: "User guide"
        contents:
        - section: "Introduction"
          contents:
          - user_guide/intro/starsim.ipynb
          - user_guide/intro/spokes.ipynb
        - section: "Basic concepts"
          contents:
          - user_guide/basics/model.ipynb
          - user_guide/basics/sim.ipynb
          - user_guide/basics/people.ipynb
        - section: "Modules"
          contents:
          - user_guide/modules/diseases.ipynb
          - user_guide/modules/networks.ipynb
          - user_guide/modules/demographics.ipynb
          - user_guide/modules/interventions.ipynb
          - user_guide/modules/analyzers.ipynb
          - user_guide/modules/connectors.ipynb
        - section: "Workflows"
          contents:
          - user_guide/workflows/run.ipynb
          - user_guide/workflows/calibration.ipynb
          - user_guide/workflows/samples.ipynb
          - user_guide/workflows/cloud.ipynb
        - section: "Advanced topics"
          contents:
          - user_guide/advanced/time.ipynb
          - user_guide/advanced/indexing.ipynb
          - user_guide/advanced/parameters.ipynb
          - user_guide/advanced/distributions.ipynb
          - user_guide/advanced/random.ipynb
          - user_guide/advanced/profiling.ipynb
          - user_guide/advanced/nonstandard.ipynb
      - href: whatsnew.qmd
        text: What's new
      - href: conduct.qmd
        text: Code of Conduct
      - href: contributing.qmd
        text: Contributing
      - href: api/index.qmd
        text: API reference

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: _static/theme_overrides.css
    toc: true
    toc-depth: 3
    page-layout: full
    code-copy: true
    code-tools: true
    highlight-style: github

quartodoc:
  package: starsim
  title: API reference
  dir: api
  sections:
    - title: API reference
      desc: Full details on all classes and functions.
      contents:
        - arrays
        - calibration
        - demographics
        - disease
        - distributions
        - interventions
        - loop
        - modules
        - networks
        - parameters
        - people
        - products
        - results
        - run
        - samples
        - settings
        - sim
        - time
        - utils
