#!/usr/bin/env python
#
# Build documentation with Quarto; usage is simply:
# ./build_docs
#
# To execute notebooks, run
# ./build_docs 1

import os
import sys
import sciris as sc

debug = False
if len(sys.argv)>1:
    execute = int(sys.argv[1])
else:
    execute = False

def run(cmd):
    sc.printgreen(f'> {cmd}\n')
    if not debug:
        return sc.runcommand(cmd, wait=False)

T = sc.timer()

sc.heading("Building docs with Quarto...")

# Generate API documentation using quartodoc
sc.heading('Building API documentation...')
run('python -m quartodoc build')
run('python -m quartodoc interlinks')

if execute:
    sc.heading('Executing Jupyter notebooks')
    run('./execute_notebooks')

# Build the Quarto documentation
sc.heading('Rendering docs...')
run('quarto render')

# Tidy up
sc.heading("Tidying outputs...")
run('./clean_outputs')

sc.heading("Normalizing notebooks...")
run('./normalize_notebooks')

T.toc('Docs built')
print(f"\nIndex:\n{os.getcwd()}/_build/index.html")
