#!/bin/bash
#
# Build documentation with Quarto; usage is simply:
# ./build_docs

# Exit on error
set -e

start=$SECONDS

echo "Building docs with Quarto..."

# Generate API documentation using quartodoc
quartodoc build

# Build the Quarto documentation
quarto render --execute-daemon

# Tidy up
echo "Tidying tutorials..."
cd tutorials; ./clean_outputs; cd ..

duration=$(( SECONDS - start ))
echo "Docs built after $duration seconds."
echo "Index:"
echo "`pwd`/_build/html/index.html"
