#!/usr/bin/env python
#
# Build documentation with Quarto; usage is simply:
# ./build_docs

import os
import sciris as sc

def run(cmd):
    return sc.runcommand(cmd, wait=False)

T = sc.timer()

sc.heading("Building docs with Quarto...")

# Generate API documentation using quartodoc
sc.heading('Building API documentation...')
run('quartodoc build')

# Build notebooks
sc.heading('Checking notebooks...')
def run_notebook(path):
    temp_path = path + '.tmp'
    run(f'quarto render {path}')

notebook_files = sc.runcommand('find -name "*.ipynb"')


# Build the Quarto documentation
sc.heading('Rendering docs...')
run('quarto render --execute-daemon')

# Tidy up
sc.heading("Tidying tutorials...")
run('cd tutorials; ./clean_outputs; cd ..')

T.toc('Docs built')
print(f"\nIndex:\n{os.getcwd()}/_build/html/index.html")
