#!/bin/bash
#
# To run in debug mode, type
#  ./build_quarto debug
#
# To preview the documentation, type
#  ./build_quarto preview

# Exit on error
set -e

start=$SECONDS

echo "Building docs with Quarto..."

# Generate API documentation using quartodoc
quartodoc build

# Build the Quarto documentation
quarto render --execute-daemon

# Tidy up
echo "Tidying tutorials..."
cd tutorials; ./clean_outputs; cd ..

duration=$(( SECONDS - start ))
echo "Docs built after $duration seconds."
echo "Index:"
echo "`pwd`/_build/html/index.html"
