#!/bin/bash
# Delete all temporary and build files

# Exit on error
set -e

start=$SECONDS

# Tidy up
echo "Tidying tutorials..."
./clean_outputs

echo "Removing build files..."
rm -rvf .quarto
rm -rvf api
rm -rvf _build
rm -rvf _freeze
rm -rvf .jupyter_cache
rm -rvf tutorials/.jupyter_cache/
rm -rvf user_guide/.jupyter_cache/
rm -vf objects.json

duration=$(( SECONDS - start ))
echo "Cleaned after $duration seconds."
