name: Starsim cron tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight UTC

jobs:
  ci-tests:
    uses: ./.github/workflows/tests.yaml
  downstream-tests:
    uses: ./.github/workflows/test_models.yaml