# Run downstream tests on Starsim models.
#
# Current supported models are:
#   1. STIsim
#   2. FPsim
#
# TBC:
# - HPVsim (not in the Starsim framework)
# - TBsim (still in beta)
# - Typhoidsim (still in beta)
# - Rotasim (still in beta)

name: Downstream
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  test_stisim:
    name: STIsim tests
    timeout-minutes: 10
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.14']
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Starsim
        run: pip install -e .

      - name: Check out HPVsim
        uses: actions/checkout@v6
        with:
          repository: 'starsimhub/stisim'
          path: 'stisim'

      - name: Install STIsim
        working-directory: ./stisim
        run: pip install -e .

      - name: Install STIsim tests
        working-directory: ./stisim/tests
        run: pip install -r requirements.txt

      - name: Run STIsim tests
        working-directory: ./stisim/tests
        run: pytest test_*.py --durations=0 --junitxml=stisim-test-results.xml # Run actual tests
      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test_results
          path: stisim/tests/stisim-test-results.xml

  test_fpsim:
    name: FPsim tests
    timeout-minutes: 10
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.14']
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Starsim
        run: pip install -e .

      - name: Check out FPsim
        uses: actions/checkout@v6
        with:
          repository: 'fpsim/fpsim'
          path: 'fpsim'

      - name: Install FPsim
        working-directory: ./fpsim
        run: pip install -e .

      - name: Install FPsim tests
        working-directory: ./fpsim/tests
        run: pip install -r requirements_test.txt

      - name: Run FPsim tests
        working-directory: ./fpsim/tests
        run: pytest test_*.py --durations=0 --junitxml=fpsim-test-results.xml # Run actual tests
      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test_results
          path: fpsim/tests/fpsim-test-results.xml