# Run downstream tests on Starsim models.
#
# Note: this test runs on pushes/merges to main
# and on PRs targeting main.
#
# Current supported models are:
#   1. STIsim
#   2. FPsim
#   3. HPVsim
#   4. TBsim
#
# TBC:
# - Typhoidsim (still in beta)
# - Rotasim (still in beta)

name: Downstream
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test_downstream:
    name: ${{ matrix.model }} tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {model: STIsim, repo: starsimhub/stisim, dir: stisim}
          - {model: HPVsim, repo: starsimhub/hpvsim, dir: hpvsim}
          - {model: TBsim,  repo: starsimhub/tbsim,  dir: tbsim}
          - {model: FPsim,  repo: starsimhub/fpsim,  dir: fpsim}

    steps:
      - name: Checkout Starsim
        uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: Install Starsim
        run: pip install -e .

      - name: Check out ${{ matrix.model }}
        uses: actions/checkout@v7
        with:
          repository: ${{ matrix.repo }}
          path: ${{ matrix.dir }}

      - name: Install ${{ matrix.model }}
        working-directory: ./${{ matrix.dir }}
        run: pip install -e .

      - name: Install ${{ matrix.model }} test requirements
        working-directory: ./${{ matrix.dir }}/tests
        run: pip install -r requirements.txt

      - name: Download data on first load
        if: matrix.model == 'HPVsim'
        working-directory: ./${{ matrix.dir }}
        run: hpvsim-download-data

      - name: Run ${{ matrix.model }} tests
        working-directory: ./${{ matrix.dir }}/tests
        run: pytest test_*.py -n auto --durations=0 --junitxml=results.xml # Run actual tests
      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test_results-${{ matrix.dir }}
          path: ${{ matrix.dir }}/tests/results.xml
