name: Starsim CI tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install_and_test:
    timeout-minutes: 5
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.10', '3.13']
    runs-on: ${{ matrix.os }}
    name: Install and test
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Starsim
        run: pip install -e .[dev]
      - name: Run API tests
        working-directory: ./tests
        run: pytest test_*.py -n auto --durations=0 --junitxml=test-results.xml # Run actual tests
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: './tests/test-results.xml'
          check_name: 'Test Report (Python ${{ matrix.python-version }})'
